#!/bin/bash

TRAPPING=0
trap "{ echo finishing; TRAPPING=1; }" SIGINT

while :
do
  tools/updated
  RET=$?
  if [ $RET -ne 0 ]; then
    echo "error: $RET"
  fi
  if [ $TRAPPING -eq 0 ]; then
    sleep 10
  else
    echo "done"
    exit 0
  fi
done
