#!/bin/bash

set -e

verbose() {
	! test -z "$VERBOSE"
}

verbose && echo "Running tests..."
tools/test

verbose && echo "Formatting code..."
tools/format

verbose && echo "Measuring line lengths..."
go run tools/measure/measure.go

verbose && echo "Generate..."
go run tools/generate/generate.go
