#!/bin/bash

set -eo pipefail

paths=$(ls examples/*/*.go)


#SHA=$(which sha1sum)

# Weird bug on Mac, program terminating on
# which `sha1sum` command. So lets assume OS has
# shasum, and sha1sum is our fallback case.

sha=$(which shasum)
if [[ $? != 0 || $sha == "" ]]; then
	sha="sha1sum"
fi


# We going to run upgrade only if file updated.
for path in $paths; do

	hash_new=$($sha $path | awk '{print $1}')
	hash_file=$(printf "$path" | sed -e 's/\.go/\.hash/g')
	hash_old=$(awk 'NR==1{print $1}' $hash_file)

	if [[ $hash_new != $hash_old ]]; then

        printf "Updating %s\n" $path

        tools/format
        go run tools/measure/measure.go
        go run tools/generate/generate.go

	fi
done
